import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import QuaryClient from "@/provider/QuaryClient";
import { Poppins } from "next/font/google";
import "react-datepicker/dist/react-datepicker.css";
import Navbar from "@/components/navbar";
import "react-datepicker/dist/react-datepicker.css";
const inter = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  title: "Be Present ",
  description: "Generated by Be Present",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}   >
        <QuaryClient >
          <Toaster />
          <div className=" relative w-full min-h-screen ">
            <Navbar />
            {children}
          </div>

        </QuaryClient>
      </body>
    </html>
  );
}
