import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import QuaryClient from "@/provider/QuaryClient";
import { Poppins } from "next/font/google";
import "react-datepicker/dist/react-datepicker.css";
import 'react-calendar-heatmap/dist/styles.css';
import 'react-tooltip/dist/react-tooltip.css';
const inter = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  applicationName: "Be Present",
  manifest: "/manifest.json",
  title: "Be Present ",
  description: "Generated by Be Present",
};

export const viewport: Viewport = {
  themeColor: "#03050B",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}   >
        <QuaryClient >
          <Toaster position="top-right"
            reverseOrder={false} />
          <div className=" relative w-full min-h-screen ">
            {children}
          </div>

        </QuaryClient>
      </body>
    </html>
  );
}
